### ISSUE TITLE
Receding contact angles/ Advanced contact angle 

### ISSUE THREAD

**Issue by qingqi-code** [ImperialCollegeLondon/pnflow#2]
Hi,

Can I determine the receding contact angle and advanced contact angle directly without using Morrow model? I have already have the experiment data about the receding contact angle and advanced contact angle. I do not need to assign a intrinsic contact angle. In the input file it seems I must using Morrow model. Can I avoid using Morrow model and assign receding contact angle and advanced contact angle? Thank you so much for your help!

**Comment by aliraeini** [comment]
Hi Qingqi, depends, So the code uses the contact angles assigned to INIT_CONT_ANG to first (primary drainage) cycle, which only needs receding contact angles, and by choosing model 1, you can directly assign the receding contact angles here.  For the second cycle, the interface should hinge between the receding contact angle and the (water) advancing contact angle, so you can choose model 1 again and assign the advancing contact angles to the EQUIL_CON_ANG keyword which will be used in the second cycle. There is some ambiguity when and how the contact angles shall be altered from the cycle 1 to cycle 2, but the code is meant to model subsurface conditions where the cycle 1 is primary oil invasion and then wettability change and then the second cycle is a water... injection process.  

Also, there is a model 4 option which similar to Model 1 receives from user advancing contact angles but back computes receding contact angles using Morrow model 3,  in case they will be needed in a coalescence event.  

Even  more, there is another undocumented model 5  which again accepts advancing contact angles but uses a generalized  model that by default turns into Morrow model 3 (when using a default maximum separation angle of 90 degrees: @intrinsic angle of 90) but similar to Morrow model 2 accepts a (max) separation angle other than 90.  You can also implement your own model, in function  VoidElem::setContactAngle() in file polygon.cpp, lines 80-130.

**Comment by qingqi-code** [comment]
Thank you Dr. Ali! It is very helpful and I will close the issue.
