### ISSUE TITLE
Boundary condition 

### ISSUE THREAD

**Issue by qingqi-code** [ImperialCollegeLondon/pnflow#3]
Hi Dr. Ali,

I have a question about flow rate boundary condition. If I want to use flow rate boundary condition instead of pressure boundary condition to compare the impact of capillary number. What should I assign the boundary condition keywords in the input file(for example, I want to assign a constant flow rate 2cm3/min in the inlet and a constant pressure boundary condition 1 atm in the outlet  )?
![image](https://user-images.githubusercontent.com/79345265/140192665-51b84bfe-147a-4813-b242-3be45d6a24d0.png)
Thank you so much!

**Comment by aliraeini** [comment]
The viscous pressures are are not used in the displacement process in pnflow. So you can only model low flow rates for which the choice of boundary condition does not matter. In pnflow, only the T/F values are used to set the injection and fluid escape directions.

 Sorry the format is taken from [gnflow / GNM model](https://doi.org/10.1103/PhysRevE.97.023308) for my own convenience in comparing the two models.  I gnflow I did implement and test the viscous pressure drop as a perturbation but even there I rarely use it.  The pnflow model itself has not been changed by me and is more or less compatible with the [original 2003 code](http://www.imperial.ac.uk/earth-science/research/research-groups/pore-scale-modelling/software/two-phase-network-modelling-code/) .   My changes were primarily just refactoring of the code to make its workflow clearer.

**Comment by qingqi-code** [comment]
Thank you Dr. Ali!
