### ISSUE TITLE
high contact angle problem

### ISSUE THREAD

**Issue by qingqi-code** [ImperialCollegeLondon/pnflow#4]
Hi Dr. Ali,

When I ran pnflow with a contact angle larger than 45, some error occurs:
![image](https://user-images.githubusercontent.com/79345265/140863288-5c07b5e1-82a1-4736-882a-c69fec21c1b5.png)
I used a Bentheimer rock from https://imperialcollegelondon.app.box.com/v/iccpsim-bentheimer2015 and used pnextract file
```
ObjectType =  Image
NDims =	   3
ElementType = MET_UCHAR
ElementByteOrderMSB = False
ElementNumberOfChannels = 1
CompressedData = True


DimSize =        1000  1000  1000
ElementSpacing = 5.345   5.345   5.345 
Offset =         0      0      0

ElementDataFile = Bentheimer_1000c_3p0035um.raw.gz


title Bentheimer;
```
after that I ran pnflow file
```
// -*- C -*- style pnflow keywords:

TITLE  15MPa_50C;  // base name for the output files

writeStatistics true;


//NETWORK  F Berea;   // the base name for of the network file, without _link1.dat, _link2, _pore1

NETWORK  F Bentheimer;

//!cycle#  Final Sw   Final Pc   Sw steps   Compute Kr   Compute RI
cycle1:    0.03     1.00E+05     0.2          T            F;
cycle2:    1.00    -1.00E+05     0.01          T            F;
cycle3:    0.03     1.00E+05     0.2          T            F;

//!cycle# Inject from   Produce from     Boundary-condition 
//!        Left  Right   Left    Right   Type   Water  Oil  
cycle1_BC:   T     F       F       T      DP    1.00  2.00;
cycle2_BC:   T     F       F       T      DP    2.00  1.00;
cycle3_BC:   T     F       F       T      DP    1.00  2.00;

//!       x[range]
CALC_BOX:  0.1 0.9; //!bounding box for computing rel-permss

//!          (Morrow)  [range]---Distribution--Radius Hysteresis
//!            model  [bgn end] +weibull/-rand correl  adv-rec
INIT_CONT_ANG:   1   74   74  -0.2    -3.0   rMax   0.0;

EQUIL_CON_ANG:   1   85   85   -0.2   -3.0   rMax   0.0;


//FRAC_CON_ANG:   0.7 T  120 150  0.2   3.0  corr 7;// Mixed wettability


//   viscosity(Pa.s)  resistivity(Ohm.m)  density(kg/m3)    
Water  0.001               1.2                1000.0;
Oil    0.0003              1000.0             800.0;
ClayResistivity            2.0 ;

WaterOilInterface          0.03 ;//  interfacial tension (N/m)

//RAND_SEED: 1002;
//PORE_FILL_ALG: blunt2;
//PORE_FILL_WGT: 0.0 0.5 1.0 2.0 5.0 10.0;

DRAIN_SINGLETS: T;   // T for yes, F for no


//         ball-stick visualization/animation files for Paraview
//         .----------------- visualise  --------------------.
//          init   Drainage  Imbibition  corners   all steps
//visuaLight  T        T          T         F          T ;

//                write full 3D visualization files for Paraview
//         scale  resolution  .-------------- visualise  ------------------.
//         radius   (6-18)    init  oil-inj  water-inj  corners   all steps
visualize:  1.0     10        T      F          F         T         F ;

RES_FORMAT:  excel;

```
the contact angle seems can not larger over 45 degree, or it will have error like above. I will appreciate your help very much! Many thanks!

**Comment by aliraeini** [comment]
Hi Qingqi,  
Primary drainage  contact angle (INIT_CONT_ANG) values are usually set to zero or close to zero.  I know that the code does not work for values higher than 90 and the code is rarely tested for values higher than 45 degrees. If you use small drainage contact angles then you should be able to use oil-wet water-flooding scenario (EQUIL_CON_ANG values higher than 90), or at least that is how the code has been used.  Also contact angles close to 90 give the code a tougher in terms of Pc convergence.  In theory it is possible to fix this or apply quick workarounds.  Besides, there has been some development by other members of Imperial College  [pore-scale modelling team](https://www.imperial.ac.uk/earth-science/research/research-groups/pore-scale-modelling/) who you might want to contact by email as they may not watch this repository.   I am not sure their developments has been related to this issue though, as, again, high primary drainage contact angles rare not a typical use case in flow through subsurface media.
Best wishes, Ali

**Comment by qingqi-code** [comment]
Thank you Dr. Ali. That is really helpful!
